// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA1HeiyMfDCtScNhODIlNhRdaXFTX6bLs',
    appId: '1:494887919694:web:7abedd2c0797ee1cb2631f',
    messagingSenderId: '494887919694',
    projectId: 'notes-781da',
    authDomain: 'notes-781da.firebaseapp.com',
    storageBucket: 'notes-781da.firebasestorage.app',
    measurementId: 'G-Z8D05QJNQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDFtRzrl7jcSDECebS5Hf59W1u9v6Rb3s',
    appId: '1:494887919694:android:5bba8bd6b448a75eb2631f',
    messagingSenderId: '494887919694',
    projectId: 'notes-781da',
    storageBucket: 'notes-781da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM--WT4Ex168h0K9Y10QWmacABp6a9mEI',
    appId: '1:494887919694:ios:3bf67d12e341caf7b2631f',
    messagingSenderId: '494887919694',
    projectId: 'notes-781da',
    storageBucket: 'notes-781da.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM--WT4Ex168h0K9Y10QWmacABp6a9mEI',
    appId: '1:494887919694:ios:3bf67d12e341caf7b2631f',
    messagingSenderId: '494887919694',
    projectId: 'notes-781da',
    storageBucket: 'notes-781da.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA1HeiyMfDCtScNhODIlNhRdaXFTX6bLs',
    appId: '1:494887919694:web:3a75bff9fc3881d2b2631f',
    messagingSenderId: '494887919694',
    projectId: 'notes-781da',
    authDomain: 'notes-781da.firebaseapp.com',
    storageBucket: 'notes-781da.firebasestorage.app',
    measurementId: 'G-1KLGD0Q3F6',
  );
}
