// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC845Xfvp0_Szbp6cd3xCUh-39gF0EsVGg',
    appId: '1:1010480118680:web:abc87f01351f45dbb809ed',
    messagingSenderId: '1010480118680',
    projectId: 'notesapp-5c2e2',
    authDomain: 'notesapp-5c2e2.firebaseapp.com',
    storageBucket: 'notesapp-5c2e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mFHZtBku9aevji_MgxbrVX9mNuixH-4',
    appId: '1:1010480118680:android:be1a475a84352693b809ed',
    messagingSenderId: '1010480118680',
    projectId: 'notesapp-5c2e2',
    storageBucket: 'notesapp-5c2e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATBXCbPRgotFc9B-i7U7Fn6_z9WA1Myi8',
    appId: '1:1010480118680:ios:6fad581e9a58b706b809ed',
    messagingSenderId: '1010480118680',
    projectId: 'notesapp-5c2e2',
    storageBucket: 'notesapp-5c2e2.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATBXCbPRgotFc9B-i7U7Fn6_z9WA1Myi8',
    appId: '1:1010480118680:ios:6fad581e9a58b706b809ed',
    messagingSenderId: '1010480118680',
    projectId: 'notesapp-5c2e2',
    storageBucket: 'notesapp-5c2e2.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC845Xfvp0_Szbp6cd3xCUh-39gF0EsVGg',
    appId: '1:1010480118680:web:4cf20e43caa11a5cb809ed',
    messagingSenderId: '1010480118680',
    projectId: 'notesapp-5c2e2',
    authDomain: 'notesapp-5c2e2.firebaseapp.com',
    storageBucket: 'notesapp-5c2e2.firebasestorage.app',
  );
}
